version: '3.9'

services:
  web:
    build: .
    command: /entrypoint.sh  # optional, only needed if not already using this
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.dev

